url                      : https://facial-animation-data.github.io
repository_url               : "facial-animation-data.github.io"
#baseurl: "" # the subpath of your site, e.g. /blog/
#permalink: /:title/
#
title: Intuitive Facial Animation Editing based on a Generative RNN Framework
#description: Animation Data


#additional stuff
exclude:
  - Gemfile
  - Gemfile.lock


plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-relative-links


relative_links:
  enabled: true
  collections: true

include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md


theme: jekyll-theme-slate
