#url                      : https://facial-animation-data.github.io
github:
  is_project_page: false
#baseurl: "" # the subpath of your site, e.g. /blog/
#permalink: /:title/
#
title: Intuitive Facial Animation Editing based on a Generative RNN Framework
#description: Animation Data

